I have the upsert function working and such, but integrating into the 'registerUser' function in 'action.ts' is a problem. Getting a TypeError: (0 , _app_utils_pinecone__WEBPACK_IMPORTED_MODULE_5__.insertUser) is not a function. I'm not sure why it's saying it didn't import. Need to look into this issue. May have to rethink the design....